---
output: 
  flexdashboard::flex_dashboard:
    orientation: row
    vertical_layout: scroll
params:
  variable_name: "default"
  variable: rcpt_tot_val
  dfs: NULL
  title: default
---

---
title: "`r params$title`"
---
```{r setup, include=FALSE, echo = FALSE}
library(flexdashboard)
library(dplyr)
library(plotly)
library(tidyr)
library(data.table)
```

``` {r echo = FALSE}
# Assign dataframes into variables with the same name
for (name in names(dfs)) {
  assign(name, dfs[[name]])
}

variable <- params$variable
variable_name <- params$variable_name
```

```{r echo = FALSE, include = FALSE}
# Define path to the folder that contains all of the functions
folder_path <- "./dashboards/core_4_dashboards/utils"
# Define module names
file_names <- c("create_graphs.R", "create_valueboxes.R", "get_query.R", "process_data.R")

# Import all of the functions from these modules
for (file in file_names) {
  connection <- file.path(folder_path, file)
  source(connection)
}
```
# Establishment Response Summaries
## Row 
```{r echo = FALSE}
# Partition the data into response groups and check in groups and count login ids per group
valueboxes_df <- create_valuebox_df(estab_general, "estab", params, general_df)
checked_in_valueboxes_df <- valueboxes_df %>% filter(check_in_group == "Checked in")
not_checked_in_valueboxes_df <- valueboxes_df %>% filter(check_in_group == "Not checked in")
```
### 
```{r echo = FALSE}
total_checked_in_count_estab <- return_check_in_count_for_valuebox(checked_in_valueboxes_df)

create_valueboxes_general_checkin(total_checked_in_count_estab, "Checked in")
```

## Row
###
```{r echo = FALSE}

all_responded_count_checked_in <- checked_in_valueboxes_df %>%
  filter(group == "Responded") %>%
  pull(login_count)

create_valueboxes_resp_group(all_responded_count_checked_in, "Checked in", "Responded", "establishments", params)

```
### 
```{r echo = FALSE}

partial_responded_count_checked_in <- checked_in_valueboxes_df %>%
  filter(group == "Partial") %>%
  pull(login_count)

create_valueboxes_resp_group(partial_responded_count_checked_in, "Checked in", "Partial", "establishments", params)

```
###
```{r echo = FALSE}

zero_responded_count_checked_in <- checked_in_valueboxes_df %>%
  filter(group == "All responded as zero") %>%
  pull(login_count)

create_valueboxes_resp_group(zero_responded_count_checked_in, "Checked in", "All responded as zero", "establishments", params)

```
### 
```{r echo = FALSE}

NA_responded_count_checked_in <- checked_in_valueboxes_df %>%
  filter(group == "All responded as NA") %>%
  pull(login_count)

create_valueboxes_resp_group(NA_responded_count_checked_in, "Checked in", "All responded as NA", "establishments", params)

```
## Row
### Fig. 1
```{r echo = FALSE}
# Process the data before feeding in to the graph
naics_graph_df <- process_data_for_naics_graph(estab_general, "estab", "Checked in", params, general_df)

naics_graph_df <- naics_graph_df %>% filter(check_in_group == "Checked in")

# Create a NAICS sector breakdown graph
fig <- create_NAICS_breakdown_graph(naics_graph_df)

fig
```
## Row
###
```{r echo = FALSE}
total_not_checked_in_count_estab <- return_check_in_count_for_valuebox(not_checked_in_valueboxes_df)

create_valueboxes_general_checkin(total_not_checked_in_count_estab, "Not checked in")

```
## Row
### 
```{r echo = FALSE}

all_responded_count_not_checked_in <- not_checked_in_valueboxes_df %>%
  filter(group == "Responded") %>%
  pull(login_count)

create_valueboxes_resp_group(all_responded_count_not_checked_in, "Not checked in", "Responded", "establishments", params)

```
### 
```{r echo = FALSE}

partial_responded_count_not_checked_in <- not_checked_in_valueboxes_df %>%
  filter(group == "Partial") %>%
  pull(login_count)


create_valueboxes_resp_group(partial_responded_count_not_checked_in, "Not checked in", "Partial", "establishments", params)

```
### 
```{r echo = FALSE}

zero_responded_count_not_checked_in <- not_checked_in_valueboxes_df %>%
  filter(group == "All responded as zero") %>%
  pull(login_count)

create_valueboxes_resp_group(zero_responded_count_not_checked_in, "Not checked in", "All responded as zero", "establishments", params)

```
### 
```{r echo = FALSE}

NA_responded_count_not_checked_in <- not_checked_in_valueboxes_df %>%
  filter(group == "All responded as NA") %>%
  pull(login_count)


create_valueboxes_resp_group(NA_responded_count_not_checked_in, "Not checked in", "All responded as NA", "establishments", params)

```
## Row
### Fig. 2
```{r echo = FALSE}
# Process the data before feeding in to the graph
naics_graph_df <- process_data_for_naics_graph(estab_general, "estab", "Not checked in", params, general_df)

naics_graph_df <- naics_graph_df %>% filter(check_in_group == "Not checked in")

# Create a NAICS sector breakdown graph
fig <- create_NAICS_breakdown_graph(naics_graph_df)

fig
```
# KAU Response Summaries
```{r echo = FALSE}
# This chunk creates the KAU_value_boxes df
kau_value_boxes <- create_valuebox_df(KAU_general, "KAU", params, general_df)

checked_in_KAUs <- kau_value_boxes %>% filter(check_in_group == "Checked in")
not_checked_in_KAUs <- kau_value_boxes %>% filter(check_in_group == "Not checked in")
```


## Row
###
```{r echo = FALSE}
tot_checked_in_count <- return_check_in_count_for_valuebox(checked_in_KAUs)

create_valueboxes_general_checkin(tot_checked_in_count, "Checked in")
```
## Row
###
```{r echo = FALSE}

kau_checked_in <- kau_value_boxes %>%
  filter(check_in_group == "Checked in")

kau_responded_checked_in_count <- kau_checked_in %>%
  filter(group == "Responded") %>%
  pull()

create_valueboxes_resp_group(kau_responded_checked_in_count, "Checked in", "Responded", "KAUs", params)
```

###
```{r echo = FALSE}
kau_partial_checked_in_count <- kau_checked_in %>%
  filter(group == "Partial") %>%
  pull()

create_valueboxes_resp_group(kau_partial_checked_in_count, "Checked in", "Partial", "KAUs", params)
```

###
```{r echo = FALSE}
kau_resp_0_checked_in_count <- kau_checked_in %>%
  filter(group == "All responded as zero") %>%
  pull()

create_valueboxes_resp_group(kau_resp_0_checked_in_count, "Checked in", "All responded as zero", "KAUs", params)
```
###
```{r echo = FALSE}
kau_resp_NA_checked_in_count <- kau_checked_in %>%
  filter(group == "All responded as NA") %>%
  pull()

create_valueboxes_resp_group(kau_resp_NA_checked_in_count, "Checked in", "All responded as NA", "KAUs", params)
```
## Row
### Fig. 1
```{r echo = FALSE, fig.width = 8, fig.height = 4}
# Process the data before feeding in to the graph
naics_graph_df <- process_data_for_naics_graph(KAU_general, "KAU", "Checked in", params, general_df)

naics_graph_df <- naics_graph_df %>% filter(check_in_group == "Checked in")

fig <- create_NAICS_breakdown_graph(naics_graph_df)

fig
```

### Fig. 2
``` {r echo = FALSE, warning = FALSE}
MU_SU_comparison_checkedin <- aggregate_data_by_ent_typ(KAU_general, "Checked in", params, general_df)


# Create graph to compare MU and SU in terms of response groups
fig <- create_MU_SU_comparison_graph_KAU(MU_SU_comparison_checkedin)

fig

```

## Row
###
```{r echo = FALSE}
tot_not_checked_in_count <- return_check_in_count_for_valuebox(not_checked_in_KAUs)

create_valueboxes_general_checkin(tot_not_checked_in_count, "Not checked in")
```
## Row
###
```{r echo = FALSE}

kau_not_checked_in <- kau_value_boxes %>%
  filter(check_in_group == "Not checked in")

kau_responded_not_checked_in_count <- kau_not_checked_in %>%
  filter(group == "Responded") %>%
  pull()

create_valueboxes_resp_group(kau_responded_not_checked_in_count, "Not checked in", "Responded", "KAUs", params)
```
###
```{r echo = FALSE}
kau_partial_not_checked_in_count <- kau_not_checked_in %>%
  filter(group == "Partial") %>%
  pull()

create_valueboxes_resp_group(kau_partial_not_checked_in_count, "Not checked in", "Partial", "KAUs", params)
```
###
```{r echo = FALSE}
kau_resp_0_not_checked_in_count <- kau_not_checked_in %>%
  filter(group == "All responded as zero") %>%
  pull()

create_valueboxes_resp_group(kau_resp_0_not_checked_in_count, "Not checked in", "All responded as zero", "KAUs", params)

```
###
```{r echo = FALSE}
kau_resp_NA_not_checked_in_count <- kau_not_checked_in %>%
  filter(group == "All responded as NA") %>%
  pull()

create_valueboxes_resp_group(kau_resp_NA_not_checked_in_count, "Not checked in", "All responded as NA", "KAUs", params)
```
## Row
### Fig. 3
```{r echo = FALSE, fig.width = 8, fig.height = 4}
# Process the data before feeding in to the graph
naics_graph_df <- process_data_for_naics_graph(KAU_general, "KAU", "Not checked in", params, general_df)

naics_graph_df <- naics_graph_df %>% filter(check_in_group == "Not checked in")

fig <- create_NAICS_breakdown_graph(naics_graph_df)

fig
```

### Fig. 4
```{r echo = FALSE, warning = FALSE}
MU_SU_comparison_notchecked_in <- aggregate_data_by_ent_typ(KAU_general, "Not checked in", params, general_df)

# Create comparison graph for MU and SU in response groups
fig <- create_MU_SU_comparison_graph_KAU(MU_SU_comparison_notchecked_in)
fig
```